### ISSUE TITLE
All this CSRF auto-magic is nice but poses a problem when you cannot resolve where an error comes from

### ISSUE THREAD

**Issue by Rhywden** [dotnet/AspNetCore.Docs#31082]
[EDIT by guardrex to change the article and update the Document ID]

\[EDIT by guardrex to clarify that this is a doc request, probably covered by https://github.com/dotnet/AspNetCore.Docs/issues/30647]

### Description

I added an OIDC provider as an authentication source to the new Blazor Web App. Redirecting to the login page works, logging in an redirecting back works as well.

Only then I get an error that the antiforgery-token is missing. That's nice. And for the life of me, I cannot figure out how to configure or disable this issue because you **actively hid** the token validator **somewhere**.

I'm talking about the included default "Blazor Web App" with "Individual Accounts" enabled. I have no chance to override the issue (or analyze anything really) because I cannot see where the problem is coming from. There are no visible "RequireAntiforgery" attributes anywhere.

### Page URL

None

### Content source URL

None

### Document ID

None

### Article author

Rick-Anderson

**Comment by guardrex** [comment]
Stand-by @Rhywden ... I'll get back to you shortly.

**Comment by guardrex** [comment]
I'm *BACK*. 🏃‍♂️ 

We do rely heavily on the main doc set for server-side (i.e., Blazor Web App) security guidance because this type of Blazor app relies on ASP.NET Core security/Identity API. However, we added a bit of guidance on antiforgery to the server-side Blazor security doc. Depending on how this is resolved, we'll probably end up at least covering it there. We may also cover something in the main doc set where you originally opened the issue. The current bit in the Blazor doc is at ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-8.0#antiforgery-support

... which isn't helpful at the moment for the problem that you've run into. I've updated your opening comment to point to that document at least for the time being while we figure what's going on here.

Let's work the problem via the product unit's repo. Open an issue for the product unit at ...

https://github.com/dotnet/aspnetcore/issues

You'll need to add a bit more to your issue than you have here:

* For "I get an error that the antiforgery-token is missing": Tell them exactly where are you getting the error and provide the exact error message (e.g., a stack trace is great).
* If it's purely a template-created app with Individual Accounts, you won't need to provide a repro project. If you've added code, especially code that's throwing the error, then you'll probably need to put up a minimal repro project on GitHub for the product unit engineer to pull down and inspect/run.

Please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/31082
```

... to the bottom of your opening comment so that I can follow along.

***Leave this issue open.*** We'll use this issue for tracking the doc work. This issue will close automatically later when the docs PR is merged.

**Comment by Rhywden** [comment]
Well, I actually solved the issue by sheer blind luck - sorry if I was grumpy but I was fumbling around and there's a lot of not-helpful information out there. The issue seems to stem from the fact that any OpenID-server (like Keycloak) will do a POSTback (or similar) to hand over the access tokens (or at least I'm not seeing why else Blazor would complain about the missing antiforgery token).
The previous implementations I used in .NET7 didn't really care about that *or where you pointed the Redirect URI to*. It just worked. So when I copied that particular working code from a .NET7 Blazor application to the new .NET8 which seems to be more opinionated I ran into the issue I detailed above.

So, the previous (working) config for OpenID had, among other things, a config line like this:
```
RedirectUri = "https://foo/"
```

Now the whole thing needs to look like this:
```
builder.Services.AddAuthentication(options =>
    {
        options.DefaultScheme = IdentityConstants.ApplicationScheme;
        options.DefaultSignInScheme = IdentityConstants.ExternalScheme;
    }).AddOpenIdConnect(OpenIdConnectDefaults.AuthenticationScheme, opt =>
    {
        opt.Authority = "https://openid.foo/realms/master";
        opt.ClientId = "FooDev";
        opt.Scope.Add("openid");
        opt.Scope.Add("profile");
        opt.Scope.Add("roles");
        opt.Scope.Add("offline_access");
        opt.SaveTokens = true;
        opt.ResponseType = "code";

        opt.Events.OnRedirectToIdentityProvider = async n =>
        {
            n.ProtocolMessage.RedirectUri = "https://foo/signin-oidc";
            await Task.FromResult(0);
        };
    })
    .AddIdentityCookies();
```
The need for `"https://foo/signin-oidc"` instead of `"https://foo/"` is what threw me. Problem is that OIDC seems to be the readheaded stepchild in regards to documentation. I'd very much love it if you could expand the documentation to include a common OIDC configuration - because not everyone can use 3rd party auth if it resides on external servers (GDPR and such).

**Comment by guardrex** [comment]
Thanks @Rhywden for the follow-up remarks. I'm glad you figured it out.

Currently, we only even have a vague mention of this OIDC API (`OnRedirectToIdentityProvider`) configuration in the [MFA doc](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/mfa?view=aspnetcore-8.0#openid-connect-aspnet-core-client), which wouldn't be helpful for your issue. The only other place I readily found it was in some scattered Azure B2C docs coverage over in the MS Identity Platform docs. Again, none of that would've been helpful.

> expand the documentation to include a common OIDC configuration

Yes, and that's what this issue is focused on ...

**New doc: Configure OIDC web authentication**
https://github.com/dotnet/AspNetCore.Docs/issues/30647

... and they're chatting about that right now over there. You might want to leave a brief comment over there about what happened here. I don't think you need to say much more than 'without the correct redirect URI provided to the IdP, the IdP's response got flagged 💥 by the Antiforgery Middleware' and cross-link to this issue. I assume that they will at least cover the API that you're referring to in a general way. If they decide to have a *Troubleshoot* section, then what happened here could be an entry in that section.

There are two other older issues that are loosely related because they ask for this type of coverage ...

**Generic OpenIdConnect and OAuth concept docs**
https://github.com/dotnet/AspNetCore.Docs/issues/7025

**Add document explaining the authentication system**
https://github.com/dotnet/AspNetCore.Docs/issues/4055

However, those last two aren't the best spot for a remark.

You can probably close this on the grounds that OIDC general docs are coming. I'll just reset the labels and title for historical purposes.

**Comment by M4SX5** [comment]
Hi @Rhywden and @guardrex 

I came across the exactly same issue as you. Using Keycloak, upgrading from .NET 7 to .NET 8. Worked fine in .NET 7 but in .NET 8 I get reconnnected Keycloak, can login myself successfully and then get redirected to my application. There I get the following error message: 

```
An unhandled exception occurred while processing the request.
InvalidOperationException: This form is being accessed with an invalid anti-forgery token. Validate the `IAntiforgeryValidationFeature` on the request before reading from the form.
Microsoft.AspNetCore.Http.Features.FormFeature.HandleUncheckedAntiforgeryValidationFeature()

AuthenticationFailureException: An error was encountered while handling the remote login.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()
```

 I copied your code:

```
builder.Services.AddAuthentication(options =>
    {
        options.DefaultScheme = IdentityConstants.ApplicationScheme;
        options.DefaultSignInScheme = IdentityConstants.ExternalScheme;
    }).AddOpenIdConnect(OpenIdConnectDefaults.AuthenticationScheme, opt =>
    {
        opt.Authority = "https://openid.foo/realms/master";
        opt.ClientId = "FooDev";
        opt.Scope.Add("openid");
        opt.Scope.Add("profile");
        opt.Scope.Add("roles");
        opt.Scope.Add("offline_access");
        opt.SaveTokens = true;
        opt.ResponseType = "code";

        opt.Events.OnRedirectToIdentityProvider = async n =>
        {
            n.ProtocolMessage.RedirectUri = "https://foo/signin-oidc";
            await Task.FromResult(0);
        };
    })
    .AddIdentityCookies();
```
but it is still not working. I replaced https://foo/signin-oidc with my local address https://localhost:7031/signin-oidc but nothing is changing. 

As I searched through the comments the documentation is not finished yet. Could you help me solve the issue or do you have a source where I can get some further information. 

Thank you very much.

**Comment by guardrex** [comment]
The PR for the new doc is here ...

https://github.com/dotnet/AspNetCore.Docs/pull/31555

... but it isn't reviewed yet.

Open an issue on the product unit's repo for assistance ....

https://github.com/dotnet/aspnetcore/issues

Please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/pull/31555
```

... to the bottom of your opening comment so that I can follow along. I might add content to the PR based on their discussion with you about this.
