### ISSUE TITLE
Documentation ambiguous on authentication

### ISSUE THREAD

**Issue by cosmic-tiger** [dotnet/AspNetCore.Docs#31886]
### Description

Document location:
https://learn.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-8.0#client-side-blazor-authentication

In Documentation, under section "Client-side Blazor authentication" , quote:
In client-side Blazor apps, authentication checks can be bypassed because all client-side code can be modified by users. The same is true for all client-side app technologies, including JavaScript SPA frameworks and native apps for any operating system.
Unquote.
And then, immediately after the above, it proceeds with instructions to install an "authorisation" package.

This reads quite confusingly, as it says authentication can be bypassed, but then tells you how to do it anyway with no further explaination. It then follows this with instructions to install an "authorisation" package rather than "authentication". 

It does shortly after say "For more information, see link "Secure ASP.NET Core Blazor WebAssembly"]  which offers a bit more information on the possibility of tampering. Also later on it explains that that you do not typically used Authentication directly (due to no notification if there's a change in state data).

In addtion, the provided link "Secure ASP.NET Core Blazor WebAssembly" mentioned above discusses authentication/authorisation but differs to that in the original article. The two articles seemingly offer documentation on the same subject, but contradict each other and do not complement each other.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/index.md

### Document ID

1247ee64-fbc9-ce29-0710-f6e59380f5ee

### Article author

@guardrex

**Comment by guardrex** [comment]
Hello @cosmic-tiger ...

The remark can possibly be improved with a little bit more qualification (the emphasis is added phrasing) ...

> In client-side Blazor apps, ***client-side*** authentication checks can be bypassed because all client-side code can be modified by users. The same is true for all client-side app technologies, including JavaScript SPA frameworks and native apps for any operating system.

The remark is there to remind devs that malicious users can see and tamper with anything that isn't encrypted (by the server) on the client. It doesn't literally mean that ALL authn/z can be tampered with. Example: A Razor component is placed in the app with the `[Authorize]` attribute applied to it (`@attribute [Authorize]`). That check for an authorized user is ***only on the client*** and ***can be bypassed*** by a malicious user. The page isn't really protected from being discovered and inspected, and neither is any information on it. That's what that remark means.

I propose to add "client-side" to clarify the remark. Does that make sense if I take that action?

**Comment by guardrex** [comment]
@wadepickett @Rick-Anderson @tdykstra ... No labels at all are being applied to the issues. We're not even getting the *Not Triaged* label.

**Comment by guardrex** [comment]
Fixed by #31889.

**Comment by cosmic-tiger** [comment]
Coming back to this, sorry, been away, 
Not quite sure I understand you. you mention "It doesn't literally mean that ALL authn/z can be tampered with." Can you clarify this at all, ie which authn/z cannot be tampered with? 

Also, the document still does not read right: it's still stating that authentication can be by-passed, but still proceeds to offer instructions on how  to implement anyway. (scenario ... new client side blazor wasm developer thinks to themselves: why bother implementing authentication if it can be by-passed? Might as well use server side)

**Comment by guardrex** [comment]
@cosmic-tiger ... I opened a new issue to address it further. I'll get it as soon as I can, but I'm swamped with work at the moment.
