### ISSUE TITLE
"What's new in ASP.NET Core 10.0" for .NET 10 Preview 5

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#35473]
### Description

cc: @danroth27 @wadepickett @tdykstra

Links ...

* Development team's release notes for P5: TBD
* [`dotnet/aspnetcore` P5 milestone filtered issues](https://github.com/dotnet/aspnetcore/pulls?q=milestone%3A10.0-preview5)

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-10.0?view=aspnetcore-9.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/release-notes/aspnetcore-10.0.md

### Document ID

a7ad4b01-2333-32d8-b759-e044edfb9102

### Platform Id

2f8fb8ab-5309-0a77-987a-c867c6517d2b

### Article author

Various

### Metadata

* ID: a7ad4b01-2333-32d8-b759-e044edfb9102
* PlatformId: 2f8fb8ab-5309-0a77-987a-c867c6517d2b 
* Service: **aspnet-core**
* Sub-service: **release-notes**

[Related Issues](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+is%3Aopen+a7ad4b01-2333-32d8-b759-e044edfb9102)

**Comment by BrennanConroy** [comment]
- [x] #35569 
- [x] #35570

PR: https://github.com/dotnet/aspnetcore/pull/61325

# Configure Custom Security Descriptors for HTTP.sys Request Queues

You can now specify a custom security descriptor for HTTP.sys request queues using the new `RequestQueueSecurityDescriptor` property on `HttpSysOptions`. This feature enables more granular control over access rights for the request queue, helping you tailor security to your application's needs.

# Why this matters

By customizing the security descriptor, you can allow or deny specific users or groups access to the request queue. This is particularly useful in scenarios where you want to restrict or delegate HTTP.sys request handling at the operating system level.

# How to use

Set the `RequestQueueSecurityDescriptor` property to a `GenericSecurityDescriptor` instance when configuring your HTTP.sys server. For example, to allow all users but deny guests:

```csharp
using System.Security.AccessControl;
using System.Security.Principal;
using Microsoft.AspNetCore.Server.HttpSys;

// Create a new security descriptor
var securityDescriptor = new CommonSecurityDescriptor(isContainer: false, isDS: false, sddlForm: string.Empty);

// Create a discretionary access control list (DACL)
var dacl = new DiscretionaryAcl(isContainer: false, isDS: false, capacity: 2);
dacl.AddAccess(
    AccessControlType.Allow,
    new SecurityIdentifier(WellKnownSidType.BuiltinUsersSid, null),
    -1,
    InheritanceFlags.None,
    PropagationFlags.None
);
dacl.AddAccess(
    AccessControlType.Deny,
    new SecurityIdentifier(WellKnownSidType.BuiltinGuestsSid, null),
    -1,
    InheritanceFlags.None,
    PropagationFlags.None
);

// Assign the DACL to the security descriptor
securityDescriptor.DiscretionaryAcl = dacl;

// Configure HTTP.sys options
var builder = WebApplication.CreateBuilder();
builder.WebHost.UseHttpSys(options =>
{
    options.RequestQueueSecurityDescriptor = securityDescriptor;
});
```

# Additional Notes

The `RequestQueueSecurityDescriptor` applies only when creating a new request queue.
This property does not affect existing request queues.
See the official documentation for more information about Windows security descriptors and their usage.

**Comment by mikekistler** [comment]
# ✔ ***Resolved***  - Add to What's New in include: 
- [x] #35578

Integrate in doc library: 

- [x] #35581
- [x] #35580
- [x] #35582

---

Here's a summary of what's new in ASP.NET Core for Web API apps in this preview release:

- [Validation in Minimal APIs](#validation-in-minimal-apis)
- [Support for generating OpenAPI 3.1](#support-for-generating-openapi-31)
- [OpenAPI metadata from XML doc comments](#openapi-metadata-from-xml-doc-comments)

## Validation in Minimal APIs









A number of small improvements and fixes have been made to the validation generator for Minimal APIs that was introduced in preview 4.

To support future work in the space, the underlying validation resolver APIs used to support minimal API validation have been marked as experimental. However, the top-level `AddValidation` APIs and the built-in validation filter are non-experimental.

## Support for generating OpenAPI 3.1



The OpenAPI.NET library used in ASP.NET Core OpenAPI document generation has been upgraded to [v2.0.0-preview18](https://github.com/microsoft/OpenAPI.NET/releases/tag/v2.0.0-preview.18).

## OpenAPI metadata from XML doc comments



Support for generating OpenAPI metadata from XML doc comments has been extended to extract metadata for operation responses from `<returns>` and `<response>` XML tags.

**Comment by ilonatommy** [comment]
# ✔ ***Resolved*** - Router has a `NotFoundPage` parameter.

PR: https://github.com/dotnet/aspnetcore/pull/60970

Rendering content after triggering `NavigationManager.NotFound()` method can be now handled by passing a parameter with page type to the `Router`. It is a preferred way over `NotFound` fragment because it supports routing that can be used across different applications code re-execution middleware, including non-blazor ones. If `NotFound` fragment is defined together with `NotFoundPage`, the page has higher priority.

```html
<Router AppAssembly="@typeof(Program).Assembly" NotFoundPage="typeof(Pages.NotFound)">
    <Found Context="routeData">
        <RouteView RouteData="@routeData" />
        <FocusOnNavigate RouteData="@routeData" Selector="h1" />
    </Found>
    <NotFound>This content will be ignored because we have NotFoundPage defined.</NotFound>
</Router>
```

*Resolved by #35590.*

**Comment by wadepickett** [comment]
@guardrex, For [Router has a NotFoundPage parametRer ](https://github.com/dotnet/AspNetCore.Docs/issues/35473#issuecomment-2921574247) is this limited to effecting Blazor docs or more than that?  Not clear to me yet.

**Comment by guardrex** [comment]
Blazor only. I'll resolve the coverage shortly. We still have a minute until Tuesday's release, and this should be quick to resolve when I reach it.

**Comment by guardrex** [comment]
One more day ... I should reach that ☝ (and anything else) on Friday. I'm still a bit bogged down in Managed Identity with AKV+blob DP key persistence+encryption for our BWA+Entra samples+article and in the main doc set security guidance. *I've almost got it lick'd!* 🐮👅

**Comment by danroth27** [comment]
## ⚠️ *MERGED but in need of review* ⚠️ - Blazor metrics and tracing
danroth27 marked this conversation as resolved.

.NET 10 Preview 5 introduces comprehensive metrics and tracing capabilities for Blazor applications, providing detailed observability into component lifecycle, navigation, event handling, and circuit management.

### Blazor metrics

The new metrics feature includes several meters to track different aspects of Blazor application performance:

**Microsoft.AspNetCore.Components meter:**

- **`aspnetcore.components.navigation`** - Tracks the total number of route changes in your Blazor application
- **`aspnetcore.components.event_handler`** - Measures the duration of processing browser events, including your business logic

**Microsoft.AspNetCore.Components.Lifecycle meter:**

- **`aspnetcore.components.update_parameters`** - Measures the duration of processing component parameters, including your business logic
- **`aspnetcore.components.render_diff`** - Tracks the duration of rendering batches

**Microsoft.AspNetCore.Components.Server.Circuits meter:**

For Blazor Server applications, additional circuit-specific metrics are available:

- **`aspnetcore.components.circuit.active`** - Shows the number of active circuits currently in memory
- **`aspnetcore.components.circuit.connected`** - Tracks the number of circuits connected to clients
- **`aspnetcore.components.circuit.duration`** - Measures circuit lifetime duration and provides total count

### Blazor tracing

The new activity tracing capabilities use the `Microsoft.AspNetCore.Components` activity source and provide three main types of activities:

**Circuit lifecycle tracing:**

- **`Microsoft.AspNetCore.Components.CircuitStart`** - Traces circuit initialization with format `Circuit {circuitId}`
  - Tags: `aspnetcore.components.circuit.id`
  - Links: HTTP activity

**Navigation tracing:**

- **`Microsoft.AspNetCore.Components.RouteChange`** - Tracks route changes with format `Route {route} -> {componentType}`
  - Tags: `aspnetcore.components.circuit.id`, `aspnetcore.components.type`, `aspnetcore.components.route`
  - Links: HTTP trace, circuit trace

**Event handling tracing:**

- **`Microsoft.AspNetCore.Components.HandleEvent`** - Traces event handling with format `Event {attributeName} -> {componentType}.{methodName}`
  - Tags: `aspnetcore.components.circuit.id`, `aspnetcore.components.type`, `aspnetcore.components.method`, `aspnetcore.components.attribute.name`, `error.type`
  - Links: HTTP trace, circuit trace, router trace

To enable Blazor metrics and tracing in your application, configure OpenTelemetry with the following meters and activity sources:

```csharp
builder.Services.ConfigureOpenTelemetryMeterProvider(meterProvider =>
{
    meterProvider.AddMeter("Microsoft.AspNetCore.Components");
    meterProvider.AddMeter("Microsoft.AspNetCore.Components.Lifecycle");
    meterProvider.AddMeter("Microsoft.AspNetCore.Components.Server.Circuits");
});

builder.Services.ConfigureOpenTelemetryTracerProvider(tracerProvider =>
{
    tracerProvider.AddSource("Microsoft.AspNetCore.Components");
});
```

These new observability features help you monitor and diagnose Blazor application performance, track user interactions, and understand component behavior in production environments.

*Resolved by #35590.*

**Comment by wadepickett** [comment]
@guardrex, it looks like the metrics section is waiting for [[Pre5] Blazor What's New updates by guardrex · Pull Request #35590 · dotnet/AspNetCore.Docs](https://github.com/dotnet/AspNetCore.Docs/pull/35590).   Should we publish without it if it does not make it in time?  Then update?   Everything else is in I think for WN.

**Comment by guardrex** [comment]
@wadepickett ... I think that's right. I still need review/feedback on that PR. If you're updating the WN article date to suck in the INCLUDE files, you could set it to yesterday, and I would set it to today's date later today after my PR merges.

@danroth27 ... I had to rubber 🦆 the coverage for the built-in metrics article from the PU PRs because I didn't receive content to publish. Fine with me, but *you ordered me not to do that* 🙈😆. I waited as long as I could.

**Comment by guardrex** [comment]
@wadepickett ... I see that P5 has released, so I guess you could go ahead. *Hopefully, I'll get a review soon!* 🏃‍♂

**Comment by wadepickett** [comment]
The What's New here has been merged to live a bit ago.  I also verified with the rest of the .NET docs team and made sure our summary is still correct from the main .NET What's New which points to this one for the details.
Thanks everyone!

**Comment by guardrex** [comment]
@wadepickett ... No 🎲🎲 on a PR review, so I merged it as-is for the time being (and merged to live). Pavel will look and see if/where I went wrong with any of the coverage. I'll submit a patch PR *ASAP* 🏃‍♂.

As far as this issue is concerned ... AFAIK ... we're done with it. 🎉 

**UPDATE**: There's this tho ...

https://github.com/dotnet/AspNetCore.Docs/issues/35578

... and this one ...

https://github.com/dotnet/AspNetCore.Docs/issues/35435

**Comment by wadepickett** [comment]
@guardrex, thanks, #35578 was fixed with PR #35587 yesterday, but forgot to link the issue to the PR.  Linked now.
You are right #35578 is still open which was part of the issues I took over from Rick.  It is not complete yet, working on it!  Thanks for pointing it out.

**Comment by danroth27** [comment]
@wadepickett @tdykstra Are we now done with the What's New updates for .NET 10 Preview 5? Can this issue now be closed?

**Comment by wadepickett** [comment]
@danroth27 Yes, the What's new was complete, closing.  Sorry this was left open.

**Comment by wadepickett** [comment]
@tdykstra,  what about your #35570.   It says it was fixed by PR #35616 but the issue was not closed, but looks like it should be, could you take a look?

**Comment by guardrex** [comment]
Tom updated the "Fixes" line to point to the correct issue, but GH has never been smart enough to then close the issue. It has to be done manually.

**Comment by tdykstra** [comment]
> Tom updated the "Fixes" line to point to the correct issue, but GH has never been smart enough to then close the issue. It has to be done manually.

I closed it.
